services:
  writeDB:
    image: postgres:14
    container_name: writeDB_postgres
    restart: always
    ports:
      - $MYSQL_PORT:5432
    environment:
      POSTGRES_DB: $MYSQL_DATABASE_NAME
      POSTGRES_USER: $MYSQL_USER
      POSTGRES_PASSWORD: $MYSQL_PASSWORD
    volumes:
      - ./docker/writeDB_postgres_data:/var/lib/postgresql/data

  readDB:
    image: mongo:7.0-jammy
    container_name: cqrs-mongodb
    environment:
      - MONGO_INITDB_DATABASE=cqrs_task_read
    ports:
      - "27017:27017"
    volumes:
      - ./docker/readDB_mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d:ro
    restart: unless-stopped

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.3.3
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false # Disables security for local testing
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - 9200:9200
    mem_limit: 2GB
    networks:
      - app-tier

  kibana:
    image: docker.elastic.co/kibana/kibana:9.3.3
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - app-tier

  filebeat:
    build: 
      context: ./docker/filebeat
    container_name: filebeat
    command: filebeat -e --strict.perms=false
    volumes:
      - ./logs:/src/logs
    depends_on:
      - elasticsearch
      - kibana
    networks:
      - app-tier


  postgres:
    image: postgres:14
    container_name: glitchtip_postgres
    restart: always
    environment:
      POSTGRES_DB: glitchtip
      POSTGRES_USER: glitchtip
      POSTGRES_PASSWORD: glitchtip
    volumes:
      - ./docker/glitchtip_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: glitchtip_redis
    restart: always

  web:
    image: glitchtip/glitchtip:latest
    container_name: glitchtip_web
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://glitchtip:glitchtip@postgres:5432/glitchtip
      REDIS_URL: redis://redis:6379/0
      SECRET_KEY: super-secret-key
      PORT: 8000
      EMAIL_URL: smtp://localhost:25
      GLITCHTIP_DOMAIN: http://localhost:8000
    restart: always

  worker:
    image: glitchtip/glitchtip:latest
    depends_on:
      - postgres
      - redis
    command: ./bin/run-celery.sh
    environment:
      DATABASE_URL: postgres://glitchtip:glitchtip@postgres:5432/glitchtip
      REDIS_URL: redis://redis:6379/0
      SECRET_KEY: super-secret-key
    restart: always

  migrate:
    image: glitchtip/glitchtip:latest
    depends_on:
      - postgres
      - redis
    command: python manage.py migrate
    environment:
      DATABASE_URL: postgres://glitchtip:glitchtip@postgres:5432/glitchtip
      REDIS_URL: redis://redis:6379/0
      SECRET_KEY: super-secret-key

networks:
  app-tier:
    driver: bridge